apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelai-fluent-bit-config
  namespace: sentinelai-prod
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
    [OUTPUT]
        Name         es
        Match        *
        Host         sentinelai-opensearch
        Port         9200
        Index        sentinelai-logs
