apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinelai-opensearch
  namespace: sentinelai-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinelai-opensearch
  template:
    metadata:
      labels:
        app: sentinelai-opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.16.0
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: sentinelai-opensearch
  namespace: sentinelai-prod
spec:
  selector:
    app: sentinelai-opensearch
  ports:
    - port: 9200
      targetPort: 9200
