apiVersion: v1
kind: Secret
metadata:
  name: sentinelai-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  CONTROL_PLANE_JWT_SECRET: "replace-me"
  POSTGRES_PASSWORD: "replace-me"
  KAFKA_PASSWORD: "replace-me"
  VAULT_TOKEN: "replace-me"
